Repository jonghunkwon/walog, pull requests merged in 2022-08, with the labels that each got.

#24 Feature/server repo advancement
  server/.env.dev
  server/.env.prod
  server/package-lock.json
  server/package.json
  server/src/app.ts
  server/src/config/enviroment.ts
  server/src/config/logger.ts
  server/src/lib/format.ts
  server/src/lib/posts.ts
  server/src/models/api/PostAPI.ts
  server/src/models/api/index.ts
  server/src/models/index.ts
  server/src/models/model/Post.ts
  server/src/routes/admin/posts.ts
  server/src/routes/posts.ts
  server/yarn.lock
Labels: 📮 API

#25 Feature/components
  client/components/BlogItem.tsx
  client/components/KeyVisual.tsx
  client/components/Layout.tsx
  client/components/Pagination.tsx
  client/stories/Pagination.stories.tsx
  client/styles/theme.tsx
  client/tsconfig.json
Labels: 🌼 Common

#26 skip Navigation 적용(접근성)
  client/.storybook/globals.css
  client/components/Header.tsx
  client/components/Layout.tsx
  client/styles/globalStyles.tsx
Labels: 🤔 Accessibility
